/* Dummy DATA generated by CHATGPT*/

INSERT INTO tunnels (title, message) VALUES
('First Time at ComicCon', 'Just got back from my first ComicCon — absolutely unreal. Anyone else go this year?'),
('Cosplay Mishaps', 'Share your funniest or most embarrassing cosplay moments. I’ll go first... I tripped over my own tail.'),
('Artist Alley Recommendations', 'Who are your go-to artists for prints or commissions? Drop links!'),
('Best Panels Youve Attended', 'From voice actors to obscure anime trivia — what panel blew your mind?'),
('ConCrunch Therapy Circle', 'Alright y’all, how bad is your con crunch right now? Let’s talk it out.'),
('Packing List Must-Haves', 'Beyond the obvious — what do you *always* pack that saves your con experience?'),
('Most Underrated Conventions', 'We all know the big names — what small or local con deserves more love?'),
('Con Food Hacks', 'How do you eat well (or at least survive) at a con without spending $100 a day?'),
('Meetups and Friendships', 'Ever met someone at a con who became a lifelong friend? Tell us your stories.'),
('What Con Should I Go To Next?', 'Based in the Midwest, looking for something fun but not overwhelming. Ideas?');

INSERT INTO replies (tunnel_id, parent_reply_id, message) VALUES
-- Replies to Tunnel #1: First Time at ComicCon
(1, NULL, 'Same here! The energy was wild. I spent most of Saturday in the gaming hall.'),
(1, NULL, 'Did you catch the surprise Q&A with the cast of The Boys? Insane!'),

-- Replies to Tunnel #2: Cosplay Mishaps
(2, NULL, 'I once had a wig fly off mid-pose during a cosplay contest. Iconic.'),
(2, NULL, 'My armor fell apart in the bathroom line. Gorilla Glue is now my best friend.'),

-- Replies to Tunnel #3: Artist Alley Recommendations
(3, NULL, '@InkFoxArt does amazing Persona prints!'),
(3, NULL, 'I always visit @NekoJams — they make the cutest enamel pins.'),

-- Replies to Tunnel #4: Best Panels You\'ve Attended
(4, NULL, 'The My Hero Academia panel at Anime Expo 2022 was hilarious. The VAs went off.'),
(4, NULL, 'There was a retro gaming history panel at MAGFest that was surprisingly emotional.'),

-- Replies to Tunnel #5: ConCrunch Therapy Circle
(5, NULL, 'Still stitching on my gloves and the con is *tomorrow*. Why am I like this?'),
(5, NULL, 'Hot gluing in the hotel room at 2am counts as tradition, right?');

INSERT INTO users (id, first_name, last_name, username, email, rank, password)
VALUES (1, 'Test', 'User', 'testuser', 'test@example.com', 'user', 'placeholderpassword');

