/* Dummy DATA generated by CHATGPT (with numerous edits and tweaks throughout) and Convention Data entirely from FanCons */
INSERT INTO users (first_name, last_name, username, email, rank, password) VALUES 
('Alex', 'Doe', 'aldo1344', 'aldo1344@colorado.edu', 'user', '$2a$10$HNDIEphDRPRZniXjscGPRufwXnGC6zdwP/1OsMNsml0n2Yj5X/PPC'),
('Bella', 'Smith', 'besm4621', 'besm4621@colorado.edu', 'user', '$2a$10$xCk69irCsjIPX2oJmGBzmeGCgJGHJI7BT3Hkkxf2WroVIPQXsscKe'),
('Chris', 'Brown', 'chbr5782', 'chbr5782@colorado.edu', 'user', '$2a$10$xCk69irCsjIPX2oJmGBzmeGCgJGHJI7BT3Hkkxf2WroVIPQXsscKe'),
('Darryl', 'Johnson', 'dajo1444', 'dajo1444@colorado.edu', 'user', '$2a$10$xCk69irCsjIPX2oJmGBzmeGCgJGHJI7BT3Hkkxf2WroVIPQXsscKe'),
('Leon', 'Vayedjian', 'leva5149', 'leva5149@colorado.edu', 'user', '$2y$10$PruaOATtY/iuRCMZZufqz.2t18fZUtXYEMfXHzfsLCFZc9yjZj5HC'),
('Jane', 'Smith', 'jasm1234', 'jasm1234@colorado.edu', 'user', '$2y$10$OxqM94dcbuIcmrZDfcNuK.rqDzcY3/lp97lZLJvia3UWnooLNRhRa'),
('Alex', 'Taylor', 'alta5678', 'alta5678@colorado.edu', 'user', '$2y$10$dtUYrY/1eRBhJhzoymzfMuliTn8A4A94JzNRPbnER1.FWAB2AnCLi'),
('Sophia', 'Davis', 'soda7632', 'soda7632@colorado.edu', 'user', '$2a$10$kF4Tb4AY5cZ6hIKy0LfOheJcrkt7GRQOGC.xn6Q3HXZfKg9jexSSy'),
('Ethan', 'Wilson', 'ewil1987', 'ewil1987@colorado.edu', 'user', '$2a$10$RmlKnU/jExhHlbdOP3hFpef5JLRrw44RfFwt8vLPtXmfYbDQpqcs2'),
('Olivia', 'Martinez', 'olma7845', 'olma7845@colorado.edu', 'user', '$2a$10$5VpgpxlrYXoyzDbZrmrYq.DTZja3xXkvl8wz/ZdQxtYXGB5ecgDWm'),
('Liam', 'Moore', 'limo3651', 'limo3651@colorado.edu', 'user', '$2a$10$1WxxF8Pbo79doLzTPHstzOaKrK5g5Q0fRRE0dV3zT2uG8WgD/9PY6'),
('Mason', 'Lee', 'male5379', 'male5379@colorado.edu', 'user', '$2a$10$0pQuPiKrZwaFc9erZYijYuOeU2dSTYax1d1VsBLqz6O0jdSNLKEX2'),
('Ava', 'Williams', 'avwi9283', 'avwi9283@colorado.edu', 'user', '$2a$10$jeXkZ5CZQo4Vh0z4YntJBu9FgOY4MPHQLtI./uF7l1pV9cd0OXvfq'),
('Mia', 'Taylor', 'mita3679', 'mita3679@colorado.edu', 'user', '$2a$10$FJno6NY/psjD8ah0TEXGoWi31sKj7lJ0ok2Af7xWMe8A8kffYjFzS'),
('Noah', 'Anderson', 'noan2107', 'noan2107@colorado.edu', 'user', '$2a$10$ZQYoYDWJd9HpJxbXEdOF0nFOwEdbEDlK.CcNhXn4YrX0o18H55OS6'),
('Isabella', 'Thomas', 'isth8504', 'isth8504@colorado.edu', 'user', '$2a$10$DeXA0/ys5z6.VvVbmZTjR.Cgvl48lqRG3QUCRL8J7GG78hbOay2oO'),
('Lucas', 'Jackson', 'luja4128', 'luja4128@colorado.edu', 'user', '$2a$10$kh5H2fdAfq6oH07s4HzCkBhuYXQc.88K5V7Qg7s1ntOP6d3FyHG9C'),
('Admin', 'Role', 'admin', 'admin@concave.com', 'admin', '$2a$10$B9j4S5oYU5aLGgDodvYIVeS0SA49a9nAQLG018mOJ9avSpubmRhRC'),
('Convention', 'Host', 'convention_host', 'conventionhost@concave.com', 'convention_host', '$2a$10$B9j4S5oYU5aLGgDodvYIVeS0SA49a9nAQLG018mOJ9avSpubmRhRC');

INSERT INTO badges (name, description) VALUES
('Storyteller', 'Added a bio to your profile'),
('Security Expert', 'Change your password'),
('Cave Digger', 'Create a new post in The Cave'),
('Conversation Starter', 'Reply to a post in The Cave'),
('Critique', 'Write your first review');

INSERT INTO conventions (name, location, convention_center, convention_bio, convention_image, start_date, end_date) VALUES 
('Comic-Con International: San Diego 2025', 'San Diego, CA', 'San Diego Convention Center',
'Comic-Con is the premier event for all things comics and related popular art, including movies, television, gaming, interactive multimedia, and so much more! Enjoy cosplay galore and take part in unique programming, exclusive previews, and presentations, not to mention the expansive and diverse Exhibit Hall featuring merchandise and displays representing all fandoms.',
'https://media.animecons.com/ConLogos/024/logo_C24805.png','2025-07-24', '2025-07-27'),
('Gen Con 2025', 'Indianapolis, IN', 'Indianapolis Convention Center',
'Founded in 1968 in Lake Geneva, WI by Dungeons & Dragons co-creator Gary Gygax, Gen Con is the largest annual event dedicated to tabletop gaming and culture in North America.
Each year, gamers and fans converge in Indianapolis, IN to share their love for all things gaming: from tournaments to guest appearances, exhibit hall booths to electronic games, workshops, seminars, anime, art shows, auctions, and countless other activities. In 2019, nearly 70,000 attendees and over 520 exhibitors made Gen Con their gaming destination!',
'https://media.animecons.com/ConLogos/025/logo_C25580.png','2025-07-31', '2025-08-03'),
('Fan Expo Boston 2025', 'Boston, MA', 'Boston Convention and Exhibition Center',
'If you''re into comics, sci-fi, horror, anime, gaming, or cosplay, come share our playground. You''ll feel out of this world - and right at home.
Find your fandom family at FAN EXPO Boston. All 55,000 of them.',
'https://media.animecons.com/ConLogos/023/logo_C23707.jpg','2025-08-08', '2025-08-10'),
('Anime Ultra 2025', 'San Antonio, TX', 'Rolling Oaks Mall',
'Shop our vendor hall filled with artists and anime vendors from all over Texas, in a one-stop shop! Meet the amazing actors to voice some of the best and hottest anime shows you probably watched and/or movie/tv show you''ve been binging! Learn more about the different ecchi workshops, celebrity panels, and performances happening all weekend long!',
'https://media.animecons.com/ConLogos/025/logo_C25105.png','2025-08-16', '2025-08-17'),
('Anime NYC 2025', 'New York, NY', 'Jacob K. Javits Center',
'Anime NYC is New York City’s anime convention! A showcase of the best of Japanese pop culture in the biggest city in America, Anime NYC brings anime fans together for three days of unique exhibits, exclusive screenings, and appearances by some of the biggest creators in Japan!',
'https://media.animecons.com/ConLogos/024/logo_C24957.png', '2025-08-21', '2025-08-24'),
('Windblume 2025', 'Mesquite, TX', 'Mesquite Convention Center',
'Calling all Travelers to Windblume, a festival celebrating our favorite gacha game! Meet celebrity voice actors from Genshin Impact, Honkai Star Rail, and Zenless Zone Zero!

Shop in our curated exhibit hall and artists alley, cosplay your favorite Anime and Hoyoverse characters, attend a themed authentic Japanese Maid Cafe, attend dozens of panels and programs, and party late into the night with a themed rave and after party!',
'https://media.animecons.com/ConLogos/024/logo_C24416.jpg','2025-08-22', '2025-08-24'),
('San Japan', 'San Antonio, TX', 'Henry B. Gonzalez Convention Center',
'San Japan is South Texas’ largest anime and gaming convention',
'https://media.animecons.com/ConLogo/logo_C21446.png','2025-08-29', '2025-08-31'),
('Pax West 2025','Seattle, WA', 'Seattle Convention Center',
 'PAX West is a celebration of gaming and gaming culture featuring thought-provoking panels, a massive expo hall filled with the best publishers and studios, new game demos, musical performances, tournaments, and a community experience unlike any other.',
 'https://media.animecons.com/ConLogos/025/logo_C25333.png','2025-08-29','2025-09-01'),
('Furry Migration 2025','Minneapolis, MN','Hyatt Regency Minneapolis',
'Furry Migration is an event outreach of Minnesota Furs (MNFurs), a 501c3 nonprofit organization created in 2012. MNFurs is built upon its community. It’s the heart and soul of what makes MNFurs one of the most unique furry groups in the United States. FM builds on MNFurs goal of providing a friendly atmosphere where fans of anthropomorphic animals and artwork can gather to facilitate the formation of friendships and meeting new people.',
'https://media.animecons.com/ConLogos/024/logo_C24633.png','2025-09-05','2025-09-07'),
('Retro South 2025','Wichita Falls, TX','Multi-Purpose Event Center',
'Retro South Video Game Expo is a video game & pop culture convention held annually in Wichita Falls, Texas. We prioritize bringing a community together for a weekend of fun and entertainment. We thank all attendees, guests, artists, vendors and of course the wonderful venues who give us a safe place to hold our events. We look forward to seeing each and everyone of you.',
'https://media.animecons.com/ConLogos/025/logo_C25375.png','2025-09-06','2025-09-07'),
('Arkansas Comic Con 2025','Little Rock, AR','Statehouse Convention Center',
'Arkansas Comic Con is a two-day event being held at the Statehouse Convention Center and will bring together a diverse list of guests, vendors, artists, and fan groups, in an affordable, family-friendly environment.',
'https://media.animecons.com/ConLogos/024/logo_C24277.png','2025-09-12','2025-09-14'),
('Another Furry Con 2025','Ontario, CA','Ontario Convention Center',
'Another Furry Con (AFC) - an annual furry convention in Southern California. Our convention brings together furries, artists, cosplayers, and enthusiasts for a weekend filled with fun, friendship, and community.',
'https://media.animecons.com/ConLogos/025/logo_C25548.jpg','2025-09-19','2025-09-21'),
('Alpha Omega Con 2025','Long Beach, CA','Light & Life Christian Fellowship',
'The Alpha Omega Con is the longest-running Christian-themed, family-friendly comic book convention in the United States.

The Alpha Omega Con is a prominent Christian-themed, family-friendly comic book convention in Southern California, with a legacy of celebrating faith and fandom for years.

Come join us for a Christian celebration of popular creativity where everyone, from the most enthusiastic fans to curious explorers can enjoy and share these interests in a God-honoring, family-friendly environment!',
'https://media.animecons.com/ConLogos/025/logo_C25368.png','2025-09-20','2025-09-20'),
('FanX Salt Lake Comic Convention 2025','Salt Lake City, UT','Salt Palace Convention Center',
'FanX Salt Lake is a major pop culture and comic convention held annually in Salt Lake City, Utah. Known for its vibrant celebration of all things geek culture, FanX attracts fans of comics, movies, television, cosplay, gaming, and literature. It features a packed schedule of celebrity panels, workshops, artist showcases, and interactive experiences, with attendees often dressing as their favorite characters. Past events have included appearances by actors, authors, and artists from fan-favorite franchises like Star Wars, Marvel, DC Comics, and Doctor Who, among others. The convention has grown since its inception in 2013 and has become one of the largest pop culture conventions in the United States, drawing tens of thousands of fans each year.',
'https://media.animecons.com/ConLogos/024/logo_C24672.png','2025-09-25','2025-09-27'),
('New York Comic Con 2025', 'New York, NY', 'Jacob K. Javits Center',
'New York Comic Con (NYCC) is the biggest comic and pop culture event on the East Coast. From meeting celebrities to surprise appearances, to comic creators from every corner of the globe to the top anime, cosplay, and gaming stars ... it''s always one hell of a 4-day weekend.',
'https://media.animecons.com/ConLogos/024/logo_C24806.png','2025-10-09', '2025-10-12');

INSERT INTO reviews (convention_id, user_id, rating, review, time_sent) VALUES
(1, 1, 5, 'Absolutely love Comic-Con and go every year! Great panels and guests.', '2025-01-12 14:35:00'),
(1, 2, 4, 'Been a fan of Comic-Con for years—2023 had amazing guests, but the food options could be better.', '2025-02-03 16:10:00'),
(1, 3, 3, 'Last year’s Comic-Con was okay. Some events were disorganized but still had fun.', '2025-03-08 09:20:00'),
(2, 1, 5, 'Gen Con is always my favorite—so much variety in tabletop games. Can’t wait for this year!', '2025-01-20 18:00:00'),
(2, 4, 4, 'I went back in 2022 and loved the indie games section. It can get crowded, though.', '2025-02-15 19:45:00'),
(2, 5, 3, 'Last time I went, some events ran late, but I still had a good time.', '2025-03-01 10:15:00'),
(2, 6, 5, 'Went in 2023 and it was incredible. I’m definitely planning to return this summer!', '2025-04-01 12:00:00'),
(3, 2, 4, 'Fan Expo Boston last year had amazing cosplay and decent panels. Worth checking out.', '2025-01-28 17:30:00'),
(3, 3, 5, 'Attended in 2023—absolutely fantastic experience with fellow fans!', '2025-02-20 18:45:00'),
(3, 7, 2, 'Went once and felt a bit underwhelmed. Hoping this year’s event is better.', '2025-03-15 08:50:00'),
(3, 1, 4, 'The artist alley and fan zones were the highlights for me last year.', '2025-03-30 10:25:00'),
(4, 4, 5, 'Had a blast at Anime Ultra in 2023—laid-back vibe and great panels!', '2025-01-05 15:00:00'),
(4, 5, 3, 'Checked it out last year. Vendors were cool, but the space felt cramped.', '2025-02-17 16:10:00'),
(4, 6, 4, 'Went last August and really enjoyed meeting voice actors. Hoping for even more guests this year.', '2025-03-22 17:30:00'),
(4, 2, 2, 'My experience last year wasn’t great—some events were confusing and poorly run.', '2025-04-07 09:40:00'),
(15, 3, 5, 'NYCC is always amazing—2023 was packed with A-list guests and awesome panels.', '2025-01-18 20:00:00'),
(15, 7, 4, 'Loved the surprise guests in 2022. It can get overwhelming, but it’s worth it.', '2025-02-25 21:15:00'),
(15, 1, 3, 'Great artists and panels, but the crowd was a bit much last time I went.', '2025-03-12 11:30:00'),
(1, 8, 5, 'Comic-Con 2024 was a blast! Loved the panels and met some of my favorite artists.', '2025-01-14 10:45:00'),
(1, 9, 4, 'Went for the first time last year—super fun, but the lines were brutal.', '2025-02-02 13:30:00'),
(1, 10, 3, 'Mixed feelings. Some panels were great, others felt rushed or unprepared.', '2025-03-06 12:20:00'),
(2, 11, 5, 'Gen Con blew my mind. The board game demos were endless fun.', '2025-01-27 11:15:00'),
(2, 12, 2, 'Was excited but felt overwhelmed. Needed better signage and guidance.', '2025-02-21 14:00:00'),
(2, 13, 4, 'Solid experience! Made some new friends through a late-night RPG session.', '2025-03-09 15:30:00'),
(3, 14, 5, 'Fan Expo Boston had such a great cosplay community. Felt super welcome.', '2025-01-30 16:45:00'),
(3, 15, 3, 'The schedule was tight and some rooms got overfilled, but still a decent con.', '2025-02-28 10:20:00'),
(3, 16, 4, 'Enjoyed the artists and voice actor panels. Security could be friendlier though.', '2025-03-25 09:50:00'),
(4, 17, 5, 'Anime Ultra had the best vibe—chill, nerdy, and full of energy.', '2025-01-22 18:10:00');

INSERT INTO conversations (user1_id, user2_id, user1_unread, user2_unread, created_at) VALUES
(1, 2, FALSE, TRUE, '2025-04-03 00:00:45.455904'),
(3, 1, FALSE, TRUE, '2025-04-03 00:00:45.455904'),
(2, 3, FALSE, TRUE, '2025-04-03 00:00:45.455904');

INSERT INTO messages (conversation_id, user_id, message_text, time_sent) VALUES
(1, 2, 'Hey, How are you?', '2025-04-03 00:00:45.455904'),
(1, 1, 'Im good', '2025-04-03 00:01:45.455904'),
(1, 1, 'How are you?', '2025-04-03 00:01:46.455904'),
(2, 1, 'Hey, How are you?', '2025-04-03 00:00:45.455904'),
(2, 3, 'Im good', '2025-04-03 00:01:45.455904'),
(2, 3, 'How are you?', '2025-04-03 00:01:46.455904'),   
(3, 3, 'Hey, How are you?', '2025-04-03 00:00:45.455904'),
(3, 2, 'Im good', '2025-04-03 00:01:45.455904'),
(3, 2, 'How are you?', '2025-04-03 00:01:46.455904');

INSERT INTO tunnels (user_id, convention_id, title, message) VALUES
(1, 1, 'First Time at ComicCon', 'Just got back from my first ComicCon — absolutely unreal. Anyone else go this year?'),
(3, 9, 'Cosplay Mishaps', 'Share your funniest or most embarrassing cosplay moments. I’ll go first... I tripped over my own tail.'),
(5, 7, 'Artist Alley Recommendations', 'Who are your go-to artists for prints or commissions? Drop links!'),
(7, 3, 'Best Panels Youve Attended', 'From voice actors to obscure anime trivia — what panel blew your mind?'),
(2, 2, 'ConCrunch Therapy Circle', 'Alright y’all, how bad is your con crunch right now? Let’s talk it out.'),
(4, 10, 'Packing List Must-Haves', 'Beyond the obvious — what do you *always* pack that saves your con experience?'),
(6, 11, 'Most Underrated Conventions', 'We all know the big names — what small or local con deserves more love?'),
(3, 11, 'Con Food Hacks', 'How do you eat well (or at least survive) at a con without spending $100 a day?'),
(4, 12, 'Meetups and Friendships', 'Ever met someone at a con who became a lifelong friend? Tell us your stories.'),
(5, 13, 'What Con Should I Go To Next?', 'Based in the Midwest, looking for something fun but not overwhelming. Ideas?'),
(2, 1, 'Late Night Line Chaos', 'Anyone else stuck in line for that exclusive panel last night? Wild times.'),
(6, 12, 'Board Game Demos Worth Trying?', 'Found some gems at Gen Con. What games surprised you?'),
(1, 3, 'Anime Expo Haul Showoff', 'Post your best finds from the Exhibit Hall — I’ll go first, I got a signed JoJo print!'),
(7, 13, 'First Time Cosplayer Advice?', 'Planning my first cosplay for next year. What’s something you wish you knew early on?'),
(4, 9, 'Best Swag This Year', 'Which booth had the best freebies or cool merch this year?'),
(5, 3, 'Con Travel Horror Stories', 'Lost luggage? Missed flights? What’s your most cursed con trip?'),
(3, 2, 'Photo Op Fails', 'Thought I nailed my pose with the celeb... then I saw the photo 😅 Anyone relate?'),
(6, 14, 'Convention Roommates – Yay or Nay?', 'Thinking of sharing a hotel next time. Tips or horror stories?'),
(7, 8, 'Fan Meetups That Surprised You', 'Sometimes they’re awkward, sometimes they’re amazing — share your experiences.'),
(1, 4, 'Dragon Con Parade Madness', 'The costumes this year were absolutely next level. Anyone else catch the Deadpool conga line?'),
(3, 5, 'PAX Indie Showcase Highlights', 'Which lesser-known games stood out to you this year?'),
(6, 12, 'Gen Con Dice Goblin Meet-Up', 'No shame — I bought 12 sets. Who else needs a dice intervention?'),
(4, 6, 'Fan Expo Cosplay Chess?', 'Did anyone participate or watch the cosplay chess event? Iconic.'),
(2, 1, 'Comic-Con Merch Pricing', 'Some booths were wildin’ with prices... worth it or nah?'),
(7, 3, 'Anime Expo Meet-and-Greets', 'Did anyone cry meeting their favorite VA or just me?'),
(5, 14, 'Best Panels at Dragon Con', 'Honestly, the "Villains Unleashed" panel was the best I’ve ever attended.'),
(3, 6, 'Fan Expo Overload', 'Felt like I couldn’t see everything — what do y’all prioritize on day 1?'),
(1, 5, 'PAX Panels or Freeplay?', 'Which do you usually hit first — the indie panels or jumping into the freeplay section?'),
(4, 12, 'Gen Con LARP Moment', 'I accidentally got roped into a LARP battle and somehow won. Life-changing.'),
(6, 1, 'Comic-Con Lines Ranked', 'Hall H line vs. Merch drop line... which broke your soul the most?'),
(2, 13, 'Anime Expo Artist Alley Finds', 'Picked up some stunning watercolor prints — share your faves!'),
(7, 15, 'PAX Badge Pick-Up Tips', 'Got mine in 5 minutes this year — what’s your secret strategy?'),
(5, 4, 'Unexpected Dragon Con Friends', 'Met someone over ramen who ended up being my DnD DM now.'),
(3, 5, 'Fan Expo Accessibility?', 'Big shoutout to the accessibility team this year. Anyone else feel it improved?'),
(1, 7, 'Gen Con Auction Insanity', 'People really outbid me on a potato-shaped dice bag 😭'),
(4, 5, 'PAX VR Zone?', 'Tried VR for the first time — now I need a headset. What did you try?'),
(2, 1, 'Comic-Con Offsite Events', 'Sometimes the offsite stuff is better than the con itself tbh.'),
(7, 3, 'Anime Expo Karaoke Rooms', 'I signed up on a dare... and now I think I’m debuting a J-pop cover band.'),
(6, 1, 'Dragon Con Hotel Chaos', 'How early do y’all book? I blinked and everything was sold out.');

INSERT INTO replies (user_id, tunnel_id, parent_reply_id, message) VALUES
(5, 1, NULL, 'Same here! The energy was wild. I spent most of Saturday in the gaming hall.'),
(3, 1, NULL, 'Did you catch the surprise Q&A with the cast of The Boys? Insane!'),
(4, 2, NULL, 'I once had a wig fly off mid-pose during a cosplay contest. Iconic.'),
(5, 2, NULL, 'My armor fell apart in the bathroom line. Gorilla Glue is now my best friend.'),
(7, 3, NULL, '@InkFoxArt does amazing Persona prints!'),
(1, 3, NULL, 'I always visit @NekoJams — they make the cutest enamel pins.'),
(2, 4, NULL, 'The My Hero Academia panel at Anime Expo 2022 was hilarious. The VAs went off.'),
(1, 4, NULL, 'There was a retro gaming history panel at MAGFest that was surprisingly emotional.'),
(6, 5, NULL, 'Still stitching on my gloves and the con is *tomorrow*. Why am I like this?'),
(2, 5, NULL, 'Hot gluing in the hotel room at 2am counts as tradition, right?');

INSERT INTO groups (convention_id, name, description, created_by) VALUES 
(1, 'Cosplay Crew 2025', 'A group for Comic-Con attendees who love cosplay, crafting costumes, and participating in the masquerade.', 1),
(1, 'Hall H Hype', 'A group for those camping out overnight for Hall H panels. Coordinate, share tips, and fan out over the biggest reveals!', 3),
(1, 'Cosplay Collective', 'Calling all cosplayers headed to Comic-Con! Share costume ideas, group meetups, and photos.', 10),
(2, 'Tabletop Titans', 'Board game fanatics unite! Looking to schedule multiplayer sessions and demos at Gen Con.', 14),
(2, 'Indie RPG Explorers', 'Discover and discuss the best indie RPGs showcased at Gen Con.', 5),
(2, 'Dice Goblins', 'A place for dice collectors and enthusiasts to show off their sets and trade with others.', 8),
(3, 'Boston Cosplay Meetup', 'Join this group for cosplay gatherings and photography plans during the expo.', 11),
(3, 'Superhero Squad', 'Marvel, DC, and beyond! Meet other superhero fans and plan which panels to hit together.', 6),
(4, 'Ecchi Workshop Crew', 'Want to hit every ecchi workshop? We’re planning which ones to attend and reviewing panels!', 1),
(4, 'Voice Actor Stans', 'A fan group for tracking down and meeting the awesome voice talent at Anime Ultra.', 16),
(5, 'Anime NYC After Dark', 'Join for info on late-night screenings, afterparties, and chill hangs.', 13),
(5, 'J-Pop Fans NYC', 'A hangout for J-Pop and anisong fans attending the convention.', 9),
(5, 'NYC Cosplay Kings & Queens', 'Cosplayers of all styles welcome—let’s plan group shoots in the Javits Center!', 4),
(6, 'Genshin Mains Unite', 'Share builds, plan cosplay, and coordinate meetups for your favorite Genshin characters.', 2),
(6, 'Hoyoverse Café Crew', 'Planning our group visit to the themed Maid Café—come hungry and in costume!', 7),
(7, 'NYCC First-Timers', 'New to NYCC? Join us for guides, tips, and a buddy system to navigate the con chaos!', 12),
(7, 'Panel Hoppers', 'Dedicated to hitting all the big panels—share lines, updates, and real-time tips.', 17),
(7, 'East Coast Cosplay Collective', 'For veteran and rookie cosplayers alike. Let’s shine at NYCC together!', 15);

INSERT INTO merchandise (name, price, description, details, image_url) VALUES
    ('Batman T-Shirt', 19.99, 'Comfortable Batman t-shirt', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcThYqWhMKBA-vsC8Zil0DMPHrLMk9nQQ7_ZLWBjcGmLLLa2zoY5BwBMYGMfBXy4Ws5oidB2Zh5in_ur9n6E1952HvadcQXTnLRYJuM9vsL9cUofXqQG5DCh'),

    ('Superman Poster', 15.99, 'High-quality Superman movie poster', 
    ARRAY['18x24 inches', 'Glossy finish', 'Ships in protective tube', 'Limited edition'],
    'https://i.ebayimg.com/images/g/SHUAAOSwxb1nYF3J/s-l400.jpg'),

    ('Spiderman T-Shirt', 19.99, 'Comfortable cotton spiderman t-shirt', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://m.media-amazon.com/images/I/B1pppR4gVKL._CLa%7C2140%2C2000%7C71Rm9Itk9rL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UY1000_.png'),

    ('Spiderman Poster', 15.99, 'High-quality Spiderman movie poster', 
    ARRAY['18x24 inches', 'Glossy finish', 'Ships in protective tube', 'Limited edition'],
    'https://filmartgallery.com/cdn/shop/products/Spider-Man-Vintage-Movie-Poster-Original_fc6bb063.jpg?v=1741737243'),

    ('Marvel Avengers Hat', 25.00, 'Comfortable Avengers Logo Hat', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://m.media-amazon.com/images/I/817+FA-QZsL._AC_UY1000_.jpg'),
    
    ('Absolute Flash #1 Poster', 15.99, 'High-quality Flash comic poster', 
    ARRAY['18x24 inches', 'Matte finish', 'Ships in protective tube', 'Limited edition'],
    'https://bigtimecollectibles.com/cdn/shop/files/0125DC058.jpg?v=1740366731'),

    ('Absolute Wonder Woman #1 Poster', 15.99, 'High-quality Wonder Woman poster', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://www.midtowncomics.com/images/PRODUCT/XL/2353226_xl.jpg');

   INSERT INTO merchandise (name, price, description, details, image_url) VALUES
    ('Replica Captain America Shield', 49.99, 'Metal Replica Captain America Shield', 
    ARRAY['Aluminum Alloy', '26 inch diameter'],
    'https://i.ebayimg.com/images/g/LtEAAOSwQ6djmJxq/s-l1200.png'),

    ('Bleach Ichigo Figure', 79.99, 'TYBW True Shikai Ichigo Figure', 
        ARRAY['Plastic', 'Posable', '6.1 inches Tall', 'Comes with both swords'],
        'https://m.media-amazon.com/images/I/71ggIzSvwDL.jpg'),

    ('One Piece Luffytaro Figure', 39.99, 'Wano Luffytaro Figure', 
        ARRAY['Plastic', 'Posable', '5.9 Inches Tall', 'Comes with sword'],
        'https://m.media-amazon.com/images/I/617BLYwERHL.jpg'),

    ('Future Gohan Figure', 39.99, 'Cell Saga Future Gohan Figure', 
        ARRAY['Plastic', 'Posable', '6.1 Inches Tall'],
        'https://m.media-amazon.com/images/I/518RaS2NSUL.jpg'),

    ('Naruto Village Headband', 39.99, 'Naruto Hidden Leaf Village Ninja Headband', 
        ARRAY['100% Cottan', 'Fits all', 'Machine Washable'],
        'https://i.etsystatic.com/50669206/r/il/2c9aaf/6422235079/il_fullxfull.6422235079_aq4y.jpg');

INSERT INTO user_merchandise (username, merchandise_id) VALUES
    ('aldo1344', 1),
    ('mita3679', 2),
    ('soda7632', 3),
    ('aldo1344', 4),
    ('isth8504', 5),
    ('luja4128', 6),
    ('soda7632', 7),
    ('alta5678', 8),
    ('ewil1987', 9),
    ('olma7845', 10),
    ('olma7845', 11),
    ('ewil1987', 12);
