/* Dummy DATA generated by CHATGPT*/

INSERT INTO tunnels (title, message) VALUES
('First Time at ComicCon', 'Just got back from my first ComicCon — absolutely unreal. Anyone else go this year?'),
('Cosplay Mishaps', 'Share your funniest or most embarrassing cosplay moments. I'll go first... I tripped over my own tail.'),
('Artist Alley Recommendations', 'Who are your go-to artists for prints or commissions? Drop links!'),
('Best Panels Youve Attended', 'From voice actors to obscure anime trivia — what panel blew your mind?'),
('ConCrunch Therapy Circle', 'Alright y'all, how bad is your con crunch right now? Let's talk it out.'),
('Packing List Must-Haves', 'Beyond the obvious — what do you *always* pack that saves your con experience?'),
('Most Underrated Conventions', 'We all know the big names — what small or local con deserves more love?'),
('Con Food Hacks', 'How do you eat well (or at least survive) at a con without spending $100 a day?'),
('Meetups and Friendships', 'Ever met someone at a con who became a lifelong friend? Tell us your stories.'),
('What Con Should I Go To Next?', 'Based in the Midwest, looking for something fun but not overwhelming. Ideas?');

INSERT INTO replies (tunnel_id, parent_reply_id, message) VALUES
-- Replies to Tunnel #1: First Time at ComicCon
(1, NULL, 'Same here! The energy was wild. I spent most of Saturday in the gaming hall.'),
(1, NULL, 'Did you catch the surprise Q&A with the cast of The Boys? Insane!'),

-- Replies to Tunnel #2: Cosplay Mishaps
(2, NULL, 'I once had a wig fly off mid-pose during a cosplay contest. Iconic.'),
(2, NULL, 'My armor fell apart in the bathroom line. Gorilla Glue is now my best friend.'),

-- Replies to Tunnel #3: Artist Alley Recommendations
(3, NULL, '@InkFoxArt does amazing Persona prints!'),
(3, NULL, 'I always visit @NekoJams — they make the cutest enamel pins.'),

-- Replies to Tunnel #4: Best Panels You\'ve Attended
(4, NULL, 'The My Hero Academia panel at Anime Expo 2022 was hilarious. The VAs went off.'),
(4, NULL, 'There was a retro gaming history panel at MAGFest that was surprisingly emotional.'),

-- Replies to Tunnel #5: ConCrunch Therapy Circle
(5, NULL, 'Still stitching on my gloves and the con is *tomorrow*. Why am I like this?'),
(5, NULL, 'Hot gluing in the hotel room at 2am counts as tradition, right?');


INSERT INTO users (first_name, last_name, username, email, rank, password, created_at, last_login)
VALUES 
    ('Alex', 'Doe', 'u1', 'u1@mail.com', 'user', '$2a$10$HNDIEphDRPRZniXjscGPRufwXnGC6zdwP/1OsMNsml0n2Yj5X/PPC', '2025-04-02 23:54:14.881657', '2025-04-02 23:54:14.881657'),
    ('Bella', 'Smith', 'u2', 'u2@mail.com', 'user', '$2a$10$xCk69irCsjIPX2oJmGBzmeGCgJGHJI7BT3Hkkxf2WroVIPQXsscKe', '2025-04-03 00:00:45.455904', '2025-04-03 00:00:45.455904'),
    ('Chris', 'Brown', 'u3', 'u3@mail.com', 'user', '$2a$10$xCk69irCsjIPX2oJmGBzmeGCgJGHJI7BT3Hkkxf2WroVIPQXsscKe', '2025-04-03 00:00:45.455904', '2025-04-03 00:00:45.455904'),
    ('Darryl', 'Johnson', 'u4', 'u4@mail.com', 'user', '$2a$10$xCk69irCsjIPX2oJmGBzmeGCgJGHJI7BT3Hkkxf2WroVIPQXsscKe', '2025-04-03 00:00:45.455904', '2025-04-03 00:00:45.455904');

INSERT INTO users (first_name, last_name, username, email, rank, password) VALUES
('Leon', 'Vayedjian', 'leva5149', 'leva5149@colorado.edu', 'user', '$2y$10$PruaOATtY/iuRCMZZufqz.2t18fZUtXYEMfXHzfsLCFZc9yjZj5HC'),
('Jane', 'Smith', 'jasm1234', 'jasm1234@colorado.edu', 'user', '$2y$10$OxqM94dcbuIcmrZDfcNuK.rqDzcY3/lp97lZLJvia3UWnooLNRhRa'),
('Alex', 'Taylor', 'alta5678', 'alta5678@colorado.edu', 'user', '$2y$10$dtUYrY/1eRBhJhzoymzfMuliTn8A4A94JzNRPbnER1.FWAB2AnCLi'),
('Admin', 'Role', 'admin', 'admin@example.com', 'admin', '$2a$10$B9j4S5oYU5aLGgDodvYIVeS0SA49a9nAQLG018mOJ9avSpubmRhRC'),
('Convention', 'Host', 'convention_host', 'conventionhost@example.com', 'convention_host', '$2a$10$B9j4S5oYU5aLGgDodvYIVeS0SA49a9nAQLG018mOJ9avSpubmRhRC');

INSERT INTO conversations (user1_id, user2_id, user1_unread, user2_unread, created_at)
VALUES
    (1, 2, FALSE, TRUE, '2025-04-03 00:00:45.455904'),
    (3, 1, FALSE, TRUE, '2025-04-03 00:00:45.455904'),
    (2, 3, FALSE, TRUE, '2025-04-03 00:00:45.455904');

INSERT INTO messages (conversation_id, user_id, message_text, time_sent)
VALUES
    (1, 2, 'Hey, How are you?', '2025-04-03 00:00:45.455904'),
    (1, 1, 'Im good', '2025-04-03 00:01:45.455904'),
    (1, 1, 'How are you?', '2025-04-03 00:01:46.455904'),
    
    (2, 1, 'Hey, How are you?', '2025-04-03 00:00:45.455904'),
    (2, 3, 'Im good', '2025-04-03 00:01:45.455904'),
    (2, 3, 'How are you?', '2025-04-03 00:01:46.455904'),
    
    (3, 3, 'Hey, How are you?', '2025-04-03 00:00:45.455904'),
    (3, 2, 'Im good', '2025-04-03 00:01:45.455904'),
    (3, 2, 'How are you?', '2025-04-03 00:01:46.455904');


INSERT INTO conventions (name, location, convention_center, convention_bio, convention_image, start_date, end_date) VALUES 
('Comic-Con International: San Diego 2025', 'San Diego, CA', 'San Diego Convention Center',
'Comic-Con is the premier event for all things comics and related popular art, including movies, television, gaming, interactive multimedia, and so much more! Enjoy cosplay galore and take part in unique programming, exclusive previews, and presentations, not to mention the expansive and diverse Exhibit Hall featuring merchandise and displays representing all fandoms.',
'https://media.animecons.com/ConLogos/024/logo_C24805.png','2025-07-24', '2025-07-27'),
('Gen Con 2025', 'Indianapolis, IN', 'Indianapolis Convention Center',
'Founded in 1968 in Lake Geneva, WI by Dungeons & Dragons co-creator Gary Gygax, Gen Con is the largest annual event dedicated to tabletop gaming and culture in North America.
Each year, gamers and fans converge in Indianapolis, IN to share their love for all things gaming: from tournaments to guest appearances, exhibit hall booths to electronic games, workshops, seminars, anime, art shows, auctions, and countless other activities. In 2019, nearly 70,000 attendees and over 520 exhibitors made Gen Con their gaming destination!',
'https://media.animecons.com/ConLogos/025/logo_C25580.png','2025-07-31', '2025-08-03'),
('Fan Expo Boston 2025', 'Boston, MA', 'Boston Convention and Exhibition Center',
'If you''re into comics, sci-fi, horror, anime, gaming, or cosplay, come share our playground. You''ll feel out of this world - and right at home.
Find your fandom family at FAN EXPO Boston. All 55,000 of them.',
'https://media.animecons.com/ConLogos/023/logo_C23707.jpg','2025-08-08', '2025-08-10'),
('Anime Ultra 2025', 'San Antonio, TX', 'Rolling Oaks Mall',
'Shop our vendor hall filled with artists and anime vendors from all over Texas, in a one-stop shop! Meet the amazing actors to voice some of the best and hottest anime shows you probably watched and/or movie/tv show you''ve been binging! Learn more about the different ecchi workshops, celebrity panels, and performances happening all weekend long!',
'https://media.animecons.com/ConLogos/025/logo_C25105.png','2025-08-16', '2025-08-17'),
('New York Comic Con 2025', 'New York, NY', 'Jacob K. Javits Center',
'New York Comic Con (NYCC) is the biggest comic and pop culture event on the East Coast. From meeting celebrities to surprise appearances, to comic creators from every corner of the globe to the top anime, cosplay, and gaming stars ... it''s always one hell of a 4-day weekend.',
'https://media.animecons.com/ConLogos/024/logo_C24806.png','2025-10-09', '2025-10-12');


INSERT INTO reviews (convention_id, user_id, rating, review) VALUES
(1, 1, 5, 'Absolutely loved this convention! Great panels and guests.'),
(1, 2, 4, 'Had a great time, but the food options could be better.'),
(1, 3, 3, 'It was okay. Some events were disorganized but still fun overall.');

INSERT INTO merchandise (name, price, description, details, image_url) VALUES
    ('Batman T-Shirt', 19.99, 'Comfortable Batman t-shirt', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcThYqWhMKBA-vsC8Zil0DMPHrLMk9nQQ7_ZLWBjcGmLLLa2zoY5BwBMYGMfBXy4Ws5oidB2Zh5in_ur9n6E1952HvadcQXTnLRYJuM9vsL9cUofXqQG5DCh'),

    ('Superman Poster', 15.99, 'High-quality Superman movie poster', 
    ARRAY['18x24 inches', 'Glossy finish', 'Ships in protective tube', 'Limited edition'],
    'https://i.ebayimg.com/images/g/SHUAAOSwxb1nYF3J/s-l400.jpg'),

    ('Spiderman T-Shirt', 19.99, 'Comfortable cotton spiderman t-shirt', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://m.media-amazon.com/images/I/B1pppR4gVKL._CLa%7C2140%2C2000%7C71Rm9Itk9rL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UY1000_.png'),

    ('Spiderman Poster', 15.99, 'High-quality Spiderman movie poster', 
    ARRAY['18x24 inches', 'Glossy finish', 'Ships in protective tube', 'Limited edition'],
    'https://filmartgallery.com/cdn/shop/products/Spider-Man-Vintage-Movie-Poster-Original_fc6bb063.jpg?v=1741737243'),

    ('Marvel Avengers Hat', 25.00, 'Comfortable Avengers Logo Hat', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://m.media-amazon.com/images/I/817+FA-QZsL._AC_UY1000_.jpg'),
    
    ('Absolute Flash #1 Poster', 15.99, 'High-quality Flash comic poster', 
    ARRAY['18x24 inches', 'Matte finish', 'Ships in protective tube', 'Limited edition'],
    'https://bigtimecollectibles.com/cdn/shop/files/0125DC058.jpg?v=1740366731'),

    ('Absolute Wonder Woman #1 Poster', 15.99, 'High-quality Wonder Woman poster', 
    ARRAY['100% Cotton', 'Available in S, M, L, XL', 'Machine washable', 'Unisex design'],
    'https://www.midtowncomics.com/images/PRODUCT/XL/2353226_xl.jpg');

INSERT INTO user_merchandise (username, merchandise_id) VALUES
    ('u1', 1),
    ('u1', 2),
    ('u1', 3),
    ('u1', 4),
    ('u2', 5),
    ('u2', 6),
    ('u2', 7);